# fly.toml app configuration file generated for e-mithru-backend on 2025-03-22T11:46:04+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'e-mithru-backend'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.ports]]
    port = 443
    handlers = ["http", "tls"]

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"

[processes]
  app = "npm start"  # Make sure this is correct